# version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - db_glados:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-glados}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - db

  server:
    image: 'glados/api'
    build:
      context: ./glados-api-draft-master
      cache_from:
        - 'glados/api'
    command: flask run --host 0.0.0.0
    volumes:
      - ./glados-api-draft-master/app:/app
    ports:
      - ${SERVER_PORT:-5000}:5000
    env_file:
      - .env
    depends_on:
      - db

  front:
    image: node:18
    working_dir: /app
    command: npm run serve
    env_file:
      - .env
    volumes:
      - ./glados-front-draft-master:/app
    depends_on:
      - server
    ports:
      - "8080:8080"


volumes:
  db_glados:
